secret:
  enabled: false
  data_:
    HUBOT_GITHUB_TOKEN: ""
    HUBOT_SLACK_TOKEN: ""
configmap:
  enabled: true
  data:
    HUBOT_GITHUB_EVENT_NOTIFIER_TYPES: "commit_comment,create,delete,deployment,deployment_status,issue_comment,issues,page_build,pull_request_review_comment,pull_request,push,repository,release,status,ping,pull_request_review"
    HUBOT_SLACK_ACCOUNT: "Tidepool"
    HUBOT_SLACK_ROOMS: "tidebot,github-events"
    inputToRepoMap: |-
      "{\"tidebot\":\"cluster-shared\",\"shared\":\"cluster-shared\",\"qa1\":\"cluster-qa2\",\"qa1-mirror\":\"cluster-qa2\",\"qa2-mirror\":\"cluster-qa2\",\"prd-mirror\":\"cluster-production\",\"dev\":\"cluster-dev\",\"qa2\":\"cluster-qa2\",\"int\":\"cluster-integration\",\"integration\":\"cluster-integration\",\"prd\":\"cluster-production\",\"prod\":\"cluster-production\",\"production\":\"cluster-production\",\"test\":\"integration-test\",\"stg\":\"cluster-staging\",\"staging\":\"cluster-staging\"}"
    inputToNamespaceMap: |-
      "{\"qa1\":\"qa1\",\"qa1-mirror\":\"qa1-mirror\",\"qa2-mirror\":\"qa2-mirror\",\"prd-mirror\":\"prd-mirror\",\"dev\":\"dev1\",\"qa2\":\"qa2\",\"int\":\"external\",\"integration\":\"external\",\"prd\":\"tidepool-prod\",\"prod\":\"tidepool-prod\",\"production\":\"tidepool-prod\",\"test\":\"integration-test\",\"stg\":\"staging\",\"staging\":\"staging\",\"tidebot\":\"tidebot\"}"
    serviceRepoToPackage: |-
      "{\"slack-tidebot\":\"tidebot\",\"hydrophone\":\"tidepool\",\"gatekeeper\":\"tidepool\",\"platform\":\"tidepool\",\"seagull\":\"tidepool\",\"shoreline\":\"tidepool\",\"messageapi\":\"tidepool\",\"jellyfish\":\"tidepool\",\"tidewhisperer\":\"tidepool\",\"blip\":\"tidepool\",\"export\":\"tidepool\"}"
deployment:
  podAnnotations: {}
  image: tidepool/slack-tidebot:master-5783cd86c2ed10f6f107047c6d60944e4cdadc6b
  resources: {}
  securityContext: {}
  hpa:
    enabled: false
ingress:
  certificate:
    secretName: tls
  service:
    http:
      enabled: false
    https:
      enabled: false
  gateway:
    http:
      dnsNames: []
    https:
      dnsNames: []
